plugins {
    id 'java'
}

dependencies {
    compileOnly "net.fabricmc:fabric-loader:0.16.5"
    compileOnly "net.fabricmc.fabric-api:fabric-api:0.102.1+1.21.1"

    implementation project(':rtp-core')
    implementation project(':commands-api')
    implementation project(':effects-api')
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}
