rootProject.name = 'RTP'

include 'rtp-api'
include 'rtp-core'
include 'rtp-spigot-v1_20_R1'
include 'rtp-paper-v1_20_R1'
include 'rtp-folia-v1_20_R1'
include 'rtp-spigot-v1_21_R1'
include 'rtp-paper-v1_21_R1'
include 'rtp-folia-v1_21_R1'
include 'rtp-plugin'

include 'addons:RTP_Iris_integration'
include 'addons:RTP_MixedSeedFix'
include 'addons:RTP_Glide'
include 'addons:RTP_ClaimPluginIntegrations'
// include 'addons:RTP_Domain'