rootProject.name = 'RTP'

include 'rtp-api'
include 'commands-api'
include 'effects-api'
include 'rtp-anvil'
include 'rtp-tags'
include 'rtp-core'

include 'rtp-spigot:rtp-spigot-common'
include 'rtp-paper:rtp-paper-common'
include 'rtp-folia:rtp-folia-common'

include 'rtp-spigot:rtp-spigot-v1_20_R1'
include 'rtp-paper:rtp-paper-v1_20_R1'
include 'rtp-folia:rtp-folia-v1_20_R1'
include 'rtp-spigot:rtp-spigot-v1_21_R1'
include 'rtp-paper:rtp-paper-v1_21_R1'
include 'rtp-folia:rtp-folia-v1_21_R1'
include 'rtp-spigot:rtp-spigot-v26_1_R1'
include 'rtp-paper:rtp-paper-v26_1_R1'
include 'rtp-folia:rtp-folia-v26_1_R1'
include 'rtp-plugin'
if (settings.hasProperty('includeFabric') || System.getenv('INCLUDE_FABRIC') == 'true') {
    include 'rtp-fabric'
}

//include 'addons:RTP_Iris_integration'
include 'addons:RTP_Glide'
include 'addons:RTP_ExampleAddon'