package io.github.dailystruggle.rtp.common.commands.maps;

import io.github.dailystruggle.mapsapi.PaletteIndex;
import io.github.dailystruggle.mapsapi.model.RegionBadLocations;
import io.github.dailystruggle.mapsapi.render.RegionBadLocationsRenderer;
import io.github.dailystruggle.rtp.api.maps.ChartSpec;
import io.github.dailystruggle.rtp.common.RTP;
import io.github.dailystruggle.rtp.common.selection.region.Region;
import io.github.dailystruggle.rtp.common.selection.region.selectors.memory.shapes.MemoryShape;

/**
 * Resolver for {@link ChartSpec.Kind#REGION_BAD_LOCATIONS_SHAPE}.
 *
 * <p>Produces a canvas-sized, pre-classified palette buffer for the admin
 * "Visualizations -> Region shape" entry. The buffer is shape-agnostic: it
 * is generated by sampling the region's {@link MemoryShape} via the
 * shape-API surface (no shape-specific {@code centerX/centerZ/radius}
 * enum-key coupling) and is then handed to
 * {@link RegionBadLocationsRenderer} which simply blits it.
 *
 * <p>Two-pass algorithm:
 * <ol>
 *   <li><b>Bounds discovery (leap-sample).</b> The shape exposes
 *       {@link MemoryShape#getRange()} (total enumerable in-region
 *       locations) and {@link MemoryShape#locationToXZ(long)} (location
 *       index -> block XZ). We treat one location as one unit and step
 *       through {@code [0, range)} with a leap stride sized by the canvas
 *       resolution ({@code range / (width * height)}, clamped to >= 1).
 *       The min/max XZ seen during the leap become a candidate bounding
 *       box; we then pad it (10% of the larger extent) so the disk's
 *       fringe is not clipped by aliasing in the leap.</li>
 *   <li><b>Per-pixel classification.</b> For each of {@code width *
 *       height} canvas pixels we map (px, py) back to a block coordinate
 *       (bx, bz) inside the padded bounding box, then classify:
 *       <ul>
 *         <li>{@link PaletteIndex#RED}   if {@link MemoryShape#isKnownBad(int,int)};</li>
 *         <li>{@link PaletteIndex#GREEN} if otherwise inside the region
 *             ({@link MemoryShape#contains(int,int)});</li>
 *         <li>{@link PaletteIndex#BLACK} otherwise.</li>
 *       </ul></li>
 * </ol>
 *
 * <p>Empty bad-set is no longer a failure path: with no bad keys the
 * resulting buffer is the green region disk on a black backdrop, which
 * truthfully represents "the region has not yet recorded any unsafe
 * spots" without the previous "unresolvable" reject.
 *
 * <p>Failure path: throws {@link ChartSpecResolver.UnresolvableChartSpecException}
 * only when the named region is unknown, when its shape is not a
 * {@link MemoryShape} (no location enumeration available), or when the
 * shape reports a non-positive {@code getRange()}. REQ-RTP-MAP-006 /
 * REQ-RTP-S-005 / REQ-RTP-F-008: no chunk I/O; classification only reads
 * the in-memory bad-keys cache and the shape's own enumeration.
 */
public final class RegionBadLocationsShapeResolver implements ChartSpecResolver {

    /** Cartography map dimensions (vanilla). The resolver emits a buffer
     * sized to match so the renderer's fast path can blit row-by-row. */
    private static final int BUFFER_WIDTH = 128;
    private static final int BUFFER_HEIGHT = 128;

    @Override
    public Resolution resolve(ChartSpec spec) throws UnresolvableChartSpecException {
        RTP.log(java.util.logging.Level.INFO,
                "[viz/bad-locations] resolver entry: spec="
                        + (spec == null ? "null"
                                : (spec.kind() + " region=" + spec.regionName())));
        if (spec == null) {
            throw new UnresolvableChartSpecException("spec shall not be null");
        }
        if (spec.kind() != ChartSpec.Kind.REGION_BAD_LOCATIONS_SHAPE) {
            throw new UnresolvableChartSpecException(
                    "RegionBadLocationsShapeResolver only handles REGION_BAD_LOCATIONS_SHAPE, got "
                            + spec.kind());
        }

        Region region;
        try {
            region = RTP.selectionAPI.getRegionOrDefault(spec.regionName());
        } catch (RuntimeException e) {
            throw new UnresolvableChartSpecException(
                    "no region resolved for '" + spec.regionName() + "'", e);
        }
        if (region == null) {
            throw new UnresolvableChartSpecException(
                    "no region resolved for '" + spec.regionName() + "'");
        }
        if (!(region.shape instanceof MemoryShape<?> memoryShape)) {
            throw new UnresolvableChartSpecException(
                    "region '" + region.name
                            + "' shape is not a MemoryShape; no location enumeration available");
        }

        long range;
        try {
            range = memoryShape.getRange();
        } catch (RuntimeException e) {
            throw new UnresolvableChartSpecException(
                    "region '" + region.name + "' shape getRange() failed", e);
        }
        if (range <= 0L) {
            throw new UnresolvableChartSpecException(
                    "region '" + region.name + "' shape has non-positive range " + range);
        }

        // Pass 1: leap-sample to discover an axis-aligned bounding box of
        // the shape's in-region locations. "Leap based on map scaling":
        // one canvas pixel ~= one stride of (range / pixels) locations,
        // clamped to >= 1 for tiny regions (range < pixels).
        long pixels = (long) BUFFER_WIDTH * BUFFER_HEIGHT;
        long step = Math.max(1L, range / pixels);
        int minX = Integer.MAX_VALUE;
        int maxX = Integer.MIN_VALUE;
        int minZ = Integer.MAX_VALUE;
        int maxZ = Integer.MIN_VALUE;
        int samples = 0;
        for (long i = 0L; i < range; i += step) {
            int[] xz = memoryShape.locationToXZ(i);
            if (xz == null || xz.length < 2) continue;
            int bx = xz[0];
            int bz = xz[1];
            if (bx < minX) minX = bx;
            if (bx > maxX) maxX = bx;
            if (bz < minZ) minZ = bz;
            if (bz > maxZ) maxZ = bz;
            samples++;
        }
        if (samples == 0) {
            // The shape claims non-empty range but every sample failed to
            // decode. This is a shape-implementation bug rather than a
            // user-facing reject; surface it as unresolvable.
            throw new UnresolvableChartSpecException(
                    "region '" + region.name
                            + "' shape range=" + range
                            + " but locationToXZ produced no valid samples");
        }
        // Pad the bbox a little so the leap-sampled fringe is not clipped.
        // 10% of the larger extent, minimum 1 block, ensures small shapes
        // still get a visible margin.
        int extentX = maxX - minX;
        int extentZ = maxZ - minZ;
        int pad = Math.max(1, Math.max(extentX, extentZ) / 10);
        minX -= pad; maxX += pad;
        minZ -= pad; maxZ += pad;
        long boundW = (long) maxX - minX;
        long boundH = (long) maxZ - minZ;
        if (boundW <= 0L) boundW = 1L;
        if (boundH <= 0L) boundH = 1L;

        RTP.log(java.util.logging.Level.INFO,
                "[viz/bad-locations] resolver bbox: region=" + region.name
                        + " range=" + range + " step=" + step
                        + " samples=" + samples
                        + " bbox=(" + minX + "," + minZ + ")..(" + maxX + "," + maxZ + ")"
                        + " pad=" + pad);

        // Pass 2: per-pixel classification against the shape's own
        // contains() + isKnownBad() surface. No chunk I/O.
        byte[] palette = new byte[BUFFER_WIDTH * BUFFER_HEIGHT];
        for (int py = 0; py < BUFFER_HEIGHT; py++) {
            // Map canvas y -> block z. Use long math to keep the
            // multiplication safe for very large regions.
            int bz = (int) (minZ + py * boundH / (BUFFER_HEIGHT - 1));
            int row = py * BUFFER_WIDTH;
            for (int px = 0; px < BUFFER_WIDTH; px++) {
                int bx = (int) (minX + px * boundW / (BUFFER_WIDTH - 1));
                byte color;
                if (memoryShape.contains(bx, bz)) {
                    color = memoryShape.isKnownBad(bx, bz)
                            ? PaletteIndex.RED
                            : PaletteIndex.GREEN;
                } else {
                    color = PaletteIndex.BLACK;
                }
                palette[row + px] = color;
            }
        }

        RegionBadLocations model = new RegionBadLocations(
                region.name, BUFFER_WIDTH, BUFFER_HEIGHT, palette);
        return Resolution.of(RegionBadLocationsRenderer.INSTANCE, model);
    }
}
