database: database
playerCommands: playerCommands
teleportCooldown: teleportCooldown
logging: logging
cancelDistance: cancelDistance
teleportDelay: teleportDelay
consoleCommands: consoleCommands
version: version
network: network
