#toggle logs for specific occasions
# some of these logs are not configurable due to scale
detailed_reload: false
detailed_region_init: false
command: false
teleport: true

event_changeworld: true
event_join: true
event_respawn: true
event_move: true
event_teleport: true

#output detailed info when any selection fails,
#  including failure rates and sometimes parameters for debugging
selection_failure: true

#DO NOT TOUCH VERSION NUMBER
version: "1.0"
