name: RTP
version: '${project.version}'
main: io.github.dailystruggle.rtp.bukkit.RTPBukkitPlugin
api-version: 1.13
authors: [ leaf26 ]
description: 'a fast and flexible random teleportation plugin'
softdepend: [WorldGuard, WorldEdit, PlaceholderAPI, Vault, Chunky, ChunkyBorder]

commands:
  rtp:
    description: Teleport randomly
    permission: rtp.use
    usage: |
      /rtp
  wild:
    description: Teleport randomly
    permission: rtp.use
    usage: |
      /wild

permissions:
  rtp.see:
    description: allow player to tab for rtp commands
    default: true
  rtp.use:
    description: allow player to use /rtp
    default: true
  rtp.free:
    description: use /rtp for free
    default: op
  rtp.reload:
    description: allow player to use /rtp reload
    default: op
  rtp.update:
    description: allow player to use /rtp update
    default: op
  rtp.fill:
    description: allow player to start fill tasks
    default: op
  rtp.noDelay:
    description: skip the teleport delay
    default: op
  rtp.noDelay.chunks:
    description: skip chunk loading
    default: op
  rtp.noCancel:
    description: skip teleport cancellation tasks
    default: op
  rtp.noCooldown:
    description: skip the teleport cooldown
    default: op
  rtp.delay:
    description: placeholder for custom delay values
    default: false
  rtp.cooldown:
    description: placeholder for custom cooldown values
    default: false
  rtp.other:
    description: allow player to teleport another player.
    default: op
  rtp.notme:
    description: don't let player be teleported by someone else.
    default: op
  rtp.world:
    description: allow player to specify any world they have permission for
    default: op
  rtp.worlds.*:
    description: allow player to teleport to any world from any world
    default: op
    children:
      rtp.world: true
  rtp.region:
    description: allow player to specify any region they have permission for
    default: op
  rtp.regions.*:
    description: allow player to teleport to any region
    default: op
    children:
      rtp.region: true
  rtp.unqueued:
    description: if no locations are queued, generate a new location
    default: op
  rtp.params:
    description: allow player to use custom parameters for their teleport
    default: op
    children:
      rtp.unqueued: true
  rtp.personalqueue:
    description: reserve a next location for this player
    default: false
  rtp.onevent.join:
    description: randomly teleport player on every join
    default: false
  rtp.onevent.firstJoin:
    description: randomly teleport player on player's first join
    default: false
  rtp.onevent.respawn:
    description: randomly teleport player on respawn after death
    default: false
  rtp.onevent.changeWorld:
    description: randomly teleport player upon changing worlds
    default: false
  rtp.onevent.move:
    description: randomly teleport player on movement
    default: false
  rtp.onevent.teleport:
    description: randomly teleport player on teleport, recursively
    default: false
  rtp.onevent.*:
    description: inescapable chaos
    default: false
    children:
      rtp.onevent.join: true
      rtp.onevent.respawn: true
      rtp.onevent.changeWorld: true
      rtp.onevent.move: true
      rtp.onevent.teleport: true
  rtp.biome:
    description: teleport to any biome you have permission for
    default: op
  rtp.biome.free:
    description: use the biome parameter for free
    default: op
  rtp.biome.*:
    description: use any biome type
    default: op
    children:
      rtp.biome: true
  rtp.info:
    description: see plugin info and settings
    default: op
  rtp.*:
    description: access all rtp subcommands
    default: op
    children:
      rtp.see: true
      rtp.use: true
      rtp.reload: true
      rtp.update: true
      rtp.noCooldown: true
      rtp.noDelay: true
      rtp.noDelay.chunks: true
      rtp.noCancel: true
      rtp.other: true
      rtp.notme: true
      rtp.world: true
      rtp.worlds.*: true
      rtp.region: true
      rtp.regions.*: true
      rtp.params: true
      rtp.biome: true
      rtp.biome.*: true
