plugins {
    id 'java'
    id 'com.gradleup.shadow' version '8.3.8'
}

group = 'io.github.dailystruggle'
version = '1.0-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

repositories {
    mavenCentral()
    maven { url 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/' }
}

dependencies {
    compileOnly project(':rtp-api')
    compileOnly project(':rtp-core')
    compileOnly project(':rtp-spigot-v1_20_R1')
    compileOnly project(':rtp-paper-v1_20_R1')
    compileOnly 'io.papermc:paperlib:1.0.7'
    compileOnly 'org.spigotmc:spigot-api:1.16.5-R0.1-SNAPSHOT'
}

test {
    useJUnitPlatform()
}

shadowJar {
    relocate 'io.papermc.lib', 'io.github.dailystruggle.rtp.paperlib'

    dependencies {
        exclude(project(':rtp-api'))
        exclude(project(':rtp-core'))
        exclude(project(':rtp-spigot-v1_20_R1'))
        exclude(project(':rtp-paper-v1_20_R1'))
    }

    archiveClassifier.set('') // Use the standard jar name
}

// Ensure the 'build' task uses the shadowed (rewritten) jar
assemble.dependsOn shadowJar
