package io.github.dailystruggle.rtp.common.configuration;

import io.github.dailystruggle.rtp.common.RTP;
import io.github.dailystruggle.rtp.common.mock.RTPTestSetup;
import io.github.dailystruggle.rtp.common.selection.region.selectors.memory.shapes.Circle;
import io.github.dailystruggle.rtp.common.selection.region.selectors.memory.shapes.Square;
import io.github.dailystruggle.rtp.common.selection.region.selectors.verticalAdjustors.linear.LinearAdjustor;
import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * ADR-076: the shape/vert rename maps live in hidden folders, so the registered type
 * catalog is republished to visible generated markdown under definitions/regions/.
 */
@DisplayName("shape/vert catalog is generated to a visible file")
class SelectorCatalogWriterTest {

  @TempDir
  Path tempDir;

  @BeforeEach
  void setupRTP() {
    RTPTestSetup.install(tempDir.toFile());
    RTP.addShape(new Circle());
    RTP.addShape(new Square());
    RTP.addVerticalAdjustor(new LinearAdjustor(new ArrayList<>()));
  }

  private String read(String fileName) throws Exception {
    Path path = tempDir.resolve("definitions").resolve("regions").resolve(fileName);
    assertTrue(Files.exists(path), fileName + " must be generated");
    return new String(Files.readAllBytes(path), StandardCharsets.UTF_8);
  }

  @Test
  @DisplayName("SHAPES.md lists every registered type with its settings and defaults")
  void shapeCatalog() throws Exception {
    SelectorCatalogWriter.write(tempDir.toFile());

    String body = read("SHAPES.md");
    assertTrue(body.startsWith("<!-- GENERATED BY RTP"),
        "must be marked generated so an operator does not hand-edit it");
    assertTrue(body.contains("## CIRCLE"), "registered CIRCLE type must appear");
    assertTrue(body.contains("## SQUARE"), "registered SQUARE type must appear");
    assertFalse(body.contains(".YML"),
        "factory key suffix is an internal detail and must not leak into the document");
    assertTrue(body.contains("radius"), "CIRCLE settings must be listed");
    assertTrue(body.contains("shape.name"),
        "document must name the setting the type names apply to");
  }

  @Test
  @DisplayName("VERT.md is generated alongside the shape catalog")
  void vertCatalog() throws Exception {
    SelectorCatalogWriter.write(tempDir.toFile());

    String body = read("VERT.md");
    assertTrue(body.contains("## LINEAR"), "registered LINEAR adjustor must appear");
    assertTrue(body.contains("vert.name"),
        "document must name the setting the type names apply to");
  }

  @Test
  @DisplayName("the visible catalog is not hidden and regeneration is idempotent")
  void visibleAndIdempotent() throws Exception {
    SelectorCatalogWriter.write(tempDir.toFile());
    String first = read("SHAPES.md");
    SelectorCatalogWriter.write(tempDir.toFile());
    String second = read("SHAPES.md");

    assertTrue(first.equals(second), "a second reload must not change the document");
    File file = tempDir.resolve("definitions").resolve("regions").resolve("SHAPES.md").toFile();
    assertFalse(file.getName().startsWith("."),
        "the catalog is the operator-visible counterpart to the hidden rename maps");
  }
}
