package io.github.dailystruggle.rtp.common.configuration;

import io.github.dailystruggle.rtp.common.RTP;
import io.github.dailystruggle.rtp.common.factory.Factory;
import io.github.dailystruggle.rtp.common.factory.FactoryValue;
import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.EnumMap;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;

/**
 * ADR-076 addendum: the shape/vert rename maps are hidden dotfiles
 * ({@code definitions/regions/.shape}), so the registered type catalog has no
 * operator-visible on-disk record. Emits it as generated markdown beside the region
 * files. Setting names come from each type's {@code language_mapping}, so the output
 * is already in the active locale; nothing here is hand-authored or translated.
 */
public final class SelectorCatalogWriter {

  private SelectorCatalogWriter() {}

  private static final String GENERATED_MARKER =
      "<!-- GENERATED BY RTP - edits are ignored and overwritten on /rtp reload -->";

  /**
   * Writes the shape and vertical-adjustor catalogs under {@code definitions/regions/}.
   * Never throws: a catalog is a convenience document, not load-bearing config.
   *
   * @param pluginDirectory the plugin data folder
   */
  public static void write(File pluginDirectory) {
    if (pluginDirectory == null) return;
    File dir = new File(pluginDirectory, "definitions" + File.separator + "regions");
    writeOne(dir, "SHAPES.md", "Shape catalog", "shape", RTP.factoryNames.shape);
    writeOne(dir, "VERT.md", "Vertical adjustor catalog", "vert", RTP.factoryNames.vert);
  }

  private static void writeOne(File dir, String fileName, String title, String settingKey,
                               RTP.factoryNames factoryName) {
    Factory<?> factory = RTP.factoryMap.get(factoryName);
    // Platform bootstrap registers the types; an empty factory means we are being
    // called before registration (or on a stripped assembly). Leave any prior file.
    if (factory == null || factory.map.isEmpty()) return;

    try {
      if (!dir.exists() && !dir.mkdirs() && !dir.exists()) return;
      Files.write(new File(dir, fileName).toPath(),
          render(title, settingKey, factory).getBytes(StandardCharsets.UTF_8));
    } catch (IOException | RuntimeException e) {
      RTP.log(Level.WARNING, "[RTP] failed to write " + fileName + " catalog", e);
    }
  }

  /**
   * Renders one catalog document.
   *
   * @param title       document heading
   * @param settingKey  the region setting the type names apply to ({@code shape} / {@code vert})
   * @param factory     registry holding the registered types
   * @return markdown body, LF line endings
   */
  static String render(String title, String settingKey, Factory<?> factory) {
    List<String> names = new ArrayList<>(factory.map.keySet());
    names.sort(String::compareTo);

    StringBuilder res = new StringBuilder();
    res.append(GENERATED_MARKER).append('\n').append('\n');
    res.append("# ").append(title).append('\n').append('\n');
    res.append("Types registered on this server. Use one of these names as `")
        .append(settingKey).append(".name` in `definitions/regions/<region>.yml`, or in ")
        .append("`config.yml` under `defaults.").append(settingKey).append(".name`.\n\n");
    res.append("Setting names below are shown in the active locale. A type's settings are ")
        .append("only valid as a set for that type, which is why `").append(settingKey)
        .append("` inherits as a whole block through the `\"@config\"` token.\n");

    for (String name : names) {
      FactoryValue<?> value = factory.map.get(name);
      if (value == null) continue;
      res.append('\n').append("## ").append(stripSuffix(name)).append('\n').append('\n');
      res.append("| Setting | Default |\n");
      res.append("|---------|---------|\n");
      for (Map.Entry<String, Object> row : rows(value).entrySet()) {
        res.append("| `").append(row.getKey()).append("` | `")
            .append(row.getValue()).append("` |\n");
      }
    }
    return res.toString();
  }

  private static String stripSuffix(String name) {
    return name.toUpperCase().endsWith(".YML") ? name.substring(0, name.length() - 4) : name;
  }

  // Enum declaration order, so the document ordering matches the config file ordering
  // rather than the unordered keys() set.
  @SuppressWarnings({"unchecked", "rawtypes"})
  private static Map<String, Object> rows(FactoryValue<?> value) {
    Map<String, Object> res = new java.util.LinkedHashMap<>();
    EnumMap<?, Object> data = value.getData();
    Map<Enum<?>, Object> coerced = new HashMap<>((Map) data);
    Enum<?>[] constants = (Enum<?>[]) value.myClass.getEnumConstants();
    if (constants == null) return res;
    for (Enum<?> constant : constants) {
      Object localized = value.language_mapping.get(constant.name());
      String label = (localized == null) ? constant.name() : localized.toString();
      Object def = coerced.get(constant);
      res.put(label, (def == null) ? "" : def.toString());
    }
    return res;
  }
}
