plugins {
    id 'java-library'
}

dependencies {
    implementation project(':rtp-api')
    implementation project(':rtp-core')
    compileOnly 'io.papermc.paper:paper-api:1.21.1-R0.1-SNAPSHOT'
    testImplementation 'io.papermc.paper:paper-api:1.21.1-R0.1-SNAPSHOT'
    compileOnly 'io.papermc:paperlib:1.0.8'
}

test {
    useJUnitPlatform()
}
