plugins {
    id 'java-library'
}

dependencies {
    api project(':rtp-api')

    // Core logic dependencies (platform agnostic)
    implementation 'org.yaml:snakeyaml:2.3'
    implementation('me.carleslc.Simple-YAML:Simple-Yaml:1.8.4') {
        exclude group: 'org.yaml', module: 'snakeyaml'
    }
    implementation 'io.github.dailystruggle:CommandsAPI:1.0.0-RELEASE'
    implementation 'io.github.dailystruggle:EffectsAPI:1.0.1-BETA01'
    implementation 'com.google.guava:guava:33.2.1-jre'
    compileOnly 'org.jetbrains:annotations:24.1.0'
    compileOnly 'org.popcraft:chunky-common:1.3.111'
    testImplementation 'org.popcraft:chunky-common:1.3.111'
    testRuntimeOnly 'org.xerial:sqlite-jdbc:3.45.1.0'
}

test {
    useJUnitPlatform()
}
