# --- Plugin Logging Toggles (lite) ---
# Documentation: https://github.com/DailyStruggle/RTP/wiki/Logging

# Turn each log line on or off below.
command: false              # Log player-executed RTP commands
teleport: true              # Log successful teleport events
event_changeworld: true     # Log RTP triggered by world changes
event_join: true            # Log RTP triggered on join
event_respawn: true         # Log RTP triggered on respawn
event_move: true            # Log move event processing
event_teleport: true        # Log teleport event processing
selection_failure: true     # Log info when location selection fails
system_memory_tracker: false # Debug logs for memory activity
# Lowest log level to show (SEVERE, WARNING, INFO, ... , ALL, OFF).
min_level: INFO
# DO NOT TOUCH VERSION NUMBER
version: "1.1"
