# --- Przełączniki logowania pluginu ---
# Documentation: plugins/RTP/docs/admin/CONFIGURATION.md#loggingyml--console-logging-verbosity
# Loguj wszystkie pliki przeładowane podczas /rtp reload
# @type: boolean
# @default: false
detailed_reload: false

# Loguj szczegóły inicjalizacji regionu
# @type: boolean
# @default: false
detailed_region_init: false

# Loguj komendy RTP wykonane przez graczy
# @type: boolean
# @default: false
command: false

# Loguj udane zdarzenia teleportacji
# @type: boolean
# @default: true
teleport: true

# Loguj RTP wywołane zmianą świata
# @type: boolean
# @default: true
event_changeworld: true

# Loguj RTP wywołane przy dołączeniu
# @type: boolean
# @default: true
event_join: true

# Loguj RTP wywołane przy odrodzeniu
# @type: boolean
# @default: true
event_respawn: true

# Loguj przetwarzanie zdarzeń ruchu
# @type: boolean
# @default: true
event_move: true

# Loguj przetwarzanie zdarzeń teleportacji
# @type: boolean
# @default: true
event_teleport: true

# Loguj informacje, gdy wybór lokalizacji się nie powiedzie
# @type: boolean
# @default: true
selection_failure: true

# Logi debugowania aktywności pamięci
# @type: boolean
# @default: false
system_memory_tracker: false

# Logi debugowania aktywności bazy danych
# @type: boolean
# @default: false
system_database: false

# Minimalny poziom logowania pluginu. Efektywny filtr to bardziej szczegółowy
# z tego i loggera Bukkit. ALL zachowuje zachowanie identyczne z loggerem Bukkit.
# @type: enum
# @options: [SEVERE, WARNING, INFO, CONFIG, FINE, FINER, FINEST, ALL, OFF]
# @default: ALL
min_level: "INFO"

# NIE ZMIENIAJ NUMERU WERSJI
version: 1.0
