package io.github.dailystruggle.rtp.common.tasks;

import io.github.dailystruggle.rtp.api.world.ChunkColumnProbe;
import io.github.dailystruggle.rtp.common.RTP;
import io.github.dailystruggle.rtp.common.mock.MockRTPWorld;
import io.github.dailystruggle.rtp.common.mock.RTPTestSetup;
import io.github.dailystruggle.rtp.common.selection.region.Region;
import io.github.dailystruggle.rtp.common.selection.region.RegionSettings;
import io.github.dailystruggle.rtp.common.selection.region.selectors.memory.shapes.Square;
import io.github.dailystruggle.rtp.common.selection.region.selectors.memory.shapes.enums.GenericMemoryShapeParams;
import io.github.dailystruggle.rtp.common.selection.region.selectors.verticalAdjustors.linear.LinearAdjustor;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.File;
import java.lang.reflect.Field;
import java.util.*;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.atomic.AtomicInteger;

import static org.junit.jupiter.api.Assertions.*;

@DisplayName("ScanTask advanced branch coverage tests")
class ScanTaskAdvancedCoverageTest {

    @TempDir
    File tempDir;

    private Region region;
    private MockRTPWorld world;
    private Square square;

    @BeforeEach
    void setUp() {
        RTPTestSetup.install(tempDir);
        world = new MockRTPWorld("scan_branch_world");
        square = new Square();
        square.set(GenericMemoryShapeParams.radius, 100L);
        square.set(GenericMemoryShapeParams.centerRadius, 0L);

        LinearAdjustor vert = new LinearAdjustor(new ArrayList<>());
        RegionSettings settings = new RegionSettings(
                "scan_branch_region", world, square, vert,
                false, false, 10L, 1000L, 0L, 5, 0.0, 1L, "", false);
        region = new Region("scan_branch_region", settings);
        RTP.selectionAPI.permRegionLookup.put("scan_branch_region", region);
        RTP.getInstance().scanTasks.clear();
    }

    @AfterEach
    void tearDown() {
        RTP.getInstance().scanTasks.clear();
    }

    private void setPhase(ScanTask task, int phase) throws Exception {
        Field phaseField = ScanTask.class.getDeclaredField("scanPhase");
        phaseField.setAccessible(true);
        ((AtomicInteger) phaseField.get(task)).set(phase);
    }

    private int getPhase(ScanTask task) throws Exception {
        Field phaseField = ScanTask.class.getDeclaredField("scanPhase");
        phaseField.setAccessible(true);
        return ((AtomicInteger) phaseField.get(task)).get();
    }

    @Test
    void testChunkGenerated_evaluatesProbe() throws Exception {
        ScanTask task = new ScanTask(region, 0L);

        // world returns true for isChunkGenerated by default and provides a valid probe
        CompletableFuture<Boolean> fut = task.testPos(
                region, 10L, 16, 16, 2,
                Collections.emptySet(), Collections.emptySet(), false, null);

        assertNotNull(fut);
        assertTrue(fut.isDone());
    }

    @Test
    void testChunkNotGenerated_triggersFullLoadPath() throws Exception {
        MockRTPWorld ungenWorld = new MockRTPWorld("ungen_world") {
            @Override
            public boolean isChunkGenerated(int cx, int cz) {
                return false;
            }
        };

        RegionSettings settings = new RegionSettings(
                "ungen_region", ungenWorld, square, region.getVert(),
                false, false, 10L, 1000L, 0L, 5, 0.0, 1L, "", false);
        Region ungenRegion = new Region("ungen_region", settings);

        ScanTask task = new ScanTask(ungenRegion, 0L);

        CompletableFuture<Boolean> fut = task.testPos(
                ungenRegion, 10L, 16, 16, 2,
                Collections.emptySet(), Collections.emptySet(), false, null);

        assertNotNull(fut);
    }

    @Test
    void testIsChunkGeneratedThrows_handlesExceptionGracefully() throws Exception {
        MockRTPWorld throwingWorld = new MockRTPWorld("throwing_world") {
            @Override
            public boolean isChunkGenerated(int cx, int cz) {
                throw new RuntimeException("disk error");
            }
        };

        RegionSettings settings = new RegionSettings(
                "throwing_region", throwingWorld, square, region.getVert(),
                false, false, 10L, 1000L, 0L, 5, 0.0, 1L, "", false);
        Region throwingRegion = new Region("throwing_region", settings);

        ScanTask task = new ScanTask(throwingRegion, 0L);

        CompletableFuture<Boolean> fut = task.testPos(
                throwingRegion, 10L, 16, 16, 2,
                Collections.emptySet(), Collections.emptySet(), false, null);

        assertNotNull(fut);
    }

    @Test
    void testWhenChunkNotGenerated_routesToFullLoadWithoutFlippingPhase() throws Exception {
        MockRTPWorld ungenWorld = new MockRTPWorld("prescan_ungen_world") {
            @Override
            public boolean isChunkGenerated(int cx, int cz) {
                return false;
            }
        };

        RegionSettings settings = new RegionSettings(
                "prescan_ungen_region", ungenWorld, square, region.getVert(),
                false, false, 10L, 1000L, 0L, 5, 0.0, 1L, "", false);
        Region ungenRegion = new Region("prescan_ungen_region", settings);

        ScanTask task = new ScanTask(ungenRegion, 0L);
        assertEquals(ScanTask.PHASE_PRESCAN, getPhase(task));

        CompletableFuture<Boolean> fut = task.testPos(
                ungenRegion, 10L, 16, 16, 2,
                Collections.emptySet(), Collections.emptySet(), false, null);

        assertNotNull(fut);
        // Under hybrid scan, ungenerated chunks route to full load on-demand without permanently flipping scanPhase.
        assertEquals(ScanTask.PHASE_PRESCAN, getPhase(task));
    }

    @Test
    void testExecutesFullLoadPath() throws Exception {
        ScanTask task = new ScanTask(region, 0L);

        CompletableFuture<Boolean> fut = task.testPos(
                region, 10L, 16, 16, 2,
                Collections.emptySet(), Collections.emptySet(), false, null);

        assertNotNull(fut);
    }

    @Test
    void testTryProbeFirstScan_withNullProbeFuture() {
        MockRTPWorld nullProbeWorld = new MockRTPWorld("null_probe_world") {
            @Override
            public CompletableFuture<ChunkColumnProbe> probeChunkColumn(int cx, int cz, int minY, int maxY) {
                return null;
            }
        };

        RegionSettings settings = new RegionSettings(
                "null_probe_region", nullProbeWorld, square, region.getVert(),
                false, false, 10L, 1000L, 0L, 5, 0.0, 1L, "", false);
        Region nullProbeRegion = new Region("null_probe_region", settings);

        ScanTask task = new ScanTask(nullProbeRegion, 0L);
        CompletableFuture<Boolean> fut = task.testPos(
                nullProbeRegion, 10L, 16, 16, 2,
                Collections.emptySet(), Collections.emptySet(), false, null);

        assertNotNull(fut);
    }

    @Test
    void testTryProbeFirstScan_withExceptionalProbeFuture() {
        MockRTPWorld exProbeWorld = new MockRTPWorld("ex_probe_world") {
            @Override
            public CompletableFuture<ChunkColumnProbe> probeChunkColumn(int cx, int cz, int minY, int maxY) {
                CompletableFuture<ChunkColumnProbe> f = new CompletableFuture<>();
                f.completeExceptionally(new IllegalStateException("probe boom"));
                return f;
            }
        };

        RegionSettings settings = new RegionSettings(
                "ex_probe_region", exProbeWorld, square, region.getVert(),
                false, false, 10L, 1000L, 0L, 5, 0.0, 1L, "", false);
        Region exProbeRegion = new Region("ex_probe_region", settings);

        ScanTask task = new ScanTask(exProbeRegion, 0L);
        CompletableFuture<Boolean> fut = task.testPos(
                exProbeRegion, 10L, 16, 16, 2,
                Collections.emptySet(), Collections.emptySet(), false, null);

        assertNotNull(fut);
    }

    @Test
    void testTryProbeFirstScan_withResolvedProbe_validatesBiome() {
        ChunkColumnProbe mockProbe = new ChunkColumnProbe() {
            @Override public int chunkX() { return 1; }
            @Override public int chunkZ() { return 1; }
            @Override public int minY() { return 0; }
            @Override public int maxY() { return 256; }
            @Override public OptionalInt heightmapTopY() { return OptionalInt.of(64); }
            @Override public String blockAt(int y) { return "minecraft:stone"; }
            @Override public String blockAt(int lx, int lz, int y) { return "minecraft:stone"; }
            @Override public String biomeAt(int y) { return "minecraft:ocean"; }
            @Override public boolean isAirAt(int y) { return false; }
            @Override public boolean isAirAt(int lx, int lz, int y) { return false; }
        };

        MockRTPWorld probeWorld = new MockRTPWorld("probe_world") {
            @Override
            public CompletableFuture<ChunkColumnProbe> probeChunkColumn(int cx, int cz, int minY, int maxY) {
                return CompletableFuture.completedFuture(mockProbe);
            }
        };

        RegionSettings settings = new RegionSettings(
                "probe_region", probeWorld, square, region.getVert(),
                false, false, 10L, 1000L, 0L, 5, 0.0, 1L, "", false);
        Region probeRegion = new Region("probe_region", settings);

        ScanTask task = new ScanTask(probeRegion, 0L);
        Set<String> whitelist = Set.of("PLAINS");

        CompletableFuture<Boolean> fut = task.testPos(
                probeRegion, 10L, 16, 16, 2,
                Collections.emptySet(), whitelist, false, null);

        assertTrue(fut.isDone());
        assertFalse(fut.join());
        assertTrue(square.isKnownBad(10L));
    }

    @Test
    void testKnownBadWithCachedChunkBiomeResolves() {
        square.addBadLocation(25L);

        ScanTask task = new ScanTask(region, 0L);
        CompletableFuture<Boolean> fut = task.testPos(
                region, 25L, 0, 0, 2,
                Collections.emptySet(), Collections.emptySet(), false, null);

        assertTrue(fut.isDone());
        assertFalse(fut.join());
        assertTrue(square.isKnownBad(25L));
    }

    @Test
    void testClaimBoundingBoxBlankingInAdvancedCoverage() throws Exception {
        square.set(GenericMemoryShapeParams.radius, 300L);
        square.set(GenericMemoryShapeParams.centerRadius, 0L);

        io.github.dailystruggle.rtp.common.selection.region.claim.ClaimAnchoredRegionTrackerTest.RectangularClaimBoundary boundary =
                new io.github.dailystruggle.rtp.common.selection.region.claim.ClaimAnchoredRegionTrackerTest.RectangularClaimBoundary(
                        "adv_claim_1", "scan_branch_world", 100, 100, 200, 200);

        io.github.dailystruggle.rtp.api.claim.ClaimBoundaryProvider provider =
                new io.github.dailystruggle.rtp.api.claim.ClaimBoundaryProvider() {
                    @Override
                    public String namespace() {
                        return "adv_claims";
                    }

                    @Override
                    public java.util.Optional<io.github.dailystruggle.rtp.api.claim.ClaimBoundary> getBoundary(
                            java.util.UUID playerId, String worldName) {
                        return java.util.Optional.of(boundary);
                    }

                    @Override
                    public java.util.Optional<io.github.dailystruggle.rtp.api.claim.ClaimBoundary> getBoundaryAt(
                            String worldName, int x, int z) {
                        if ("scan_branch_world".equalsIgnoreCase(worldName) && boundary.contains(x, z)) {
                            return java.util.Optional.of(boundary);
                        }
                        return java.util.Optional.empty();
                    }
                };

        io.github.dailystruggle.rtp.api.hooks.ClaimBoundaryRegistry claimRegistry =
                io.github.dailystruggle.rtp.api.RTPAPI.hooks().claimBoundaries();
        AutoCloseable claimHandle = claimRegistry.register(provider);

        AtomicInteger verifierInvocations = new AtomicInteger(0);
        AutoCloseable verifierHandle = io.github.dailystruggle.rtp.common.selection.region.GlobalRegionVerifiers.addGlobalRegionVerifier(
                loc -> {
                    if (boundary.contains(loc.x(), loc.z())) {
                        verifierInvocations.incrementAndGet();
                        return false;
                    }
                    return true;
                });

        try {
            ScanTask task = new ScanTask(region, 0L);
            setPhase(task, ScanTask.PHASE_FULLSCAN);
            long posFirst = square.xzToLocation(100, 100);
            assertTrue(posFirst >= 0);

            CompletableFuture<Boolean> futFirst = task.testPos(
                    region, posFirst, 100, 100, 2,
                    Collections.emptySet(), Collections.singleton("PLAINS"), false, null);

            assertNotNull(futFirst);
            assertFalse(futFirst.join());
            assertEquals(1, verifierInvocations.get());

            for (int x = 100; x <= 200; x += 10) {
                for (int z = 100; z <= 200; z += 10) {
                    assertTrue(square.isKnownBad(x, z), "Point (" + x + "," + z + ") must be marked bad");
                }
            }

            long posSubsequent = square.xzToLocation(150, 150);
            assertTrue(posSubsequent >= 0);
            CompletableFuture<Boolean> futSubsequent = task.testPos(
                    region, posSubsequent, 150, 150, 2,
                    Collections.emptySet(), Collections.singleton("PLAINS"), false, null);

            assertNotNull(futSubsequent);
            assertFalse(futSubsequent.join());
            assertEquals(1, verifierInvocations.get(), "Subsequent claim point must be skipped without verifier re-eval");
        } finally {
            try {
                claimHandle.close();
            } catch (Exception ignored) {
            }
            try {
                verifierHandle.close();
            } catch (Exception ignored) {
            }
        }
    }
}
