#!/usr/bin/env python3
"""One-shot maintenance tool: replace em/en dashes (U+2014 / U+2013) with an
ASCII hyphen inside Java *comments* only, leaving string/char literals alone.

Also emits a review checklist of every comment location that was touched, so the
comment prose can be reviewed session by session afterwards.

String/char-literal dashes are NOT rewritten (they may be user-facing / asserted
by tests); they are reported separately for manual follow-up.
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DASHES = {"\u2014", "\u2013"}  # em dash, en dash

# tokenizer states
NORMAL, STR, CHR, LINE_C, BLOCK_C = range(5)


def classify_line_dashes(text, start_state):
    """Yield (col, kind) for each dash char in `text`.
    kind is 'comment', 'string', or 'code'. Returns (events, end_state)."""
    state = start_state
    events = []
    i = 0
    n = len(text)
    while i < n:
        c = text[i]
        nxt = text[i + 1] if i + 1 < n else ""
        if state == NORMAL:
            if c == '"':
                state = STR
            elif c == "'":
                state = CHR
            elif c == "/" and nxt == "/":
                state = LINE_C
                i += 1
            elif c == "/" and nxt == "*":
                state = BLOCK_C
                i += 1
            elif c in DASHES:
                events.append((i, "code"))
        elif state == STR:
            if c == "\\":
                i += 1
            elif c == '"':
                state = NORMAL
            elif c in DASHES:
                events.append((i, "string"))
        elif state == CHR:
            if c == "\\":
                i += 1
            elif c == "'":
                state = NORMAL
            elif c in DASHES:
                events.append((i, "string"))
        elif state == LINE_C:
            if c in DASHES:
                events.append((i, "comment"))
        elif state == BLOCK_C:
            if c == "*" and nxt == "/":
                state = NORMAL
                i += 1
            elif c in DASHES:
                events.append((i, "comment"))
        i += 1
    # LINE_C resets at end of line
    if state == LINE_C:
        state = NORMAL
    return events, state


def process_file(path):
    with open(path, "r", encoding="utf-8") as f:
        raw = f.read()
    if not any(d in raw for d in DASHES):
        return None
    lines = raw.split("\n")
    state = NORMAL
    changed = False
    comment_hits = []  # (lineno, text_after)
    string_hits = []   # (lineno, text)
    for idx, line in enumerate(lines, start=1):
        events, state = classify_line_dashes(line, state)
        if not events:
            continue
        chars = list(line)
        touched = False
        for col, kind in events:
            if kind == "comment":
                chars[col] = "-"
                touched = True
            elif kind == "string":
                string_hits.append((idx, line.strip()))
            else:  # code - shouldn't happen; report as string bucket
                string_hits.append((idx, line.strip()))
        if touched:
            newline = "".join(chars)
            lines[idx - 1] = newline
            comment_hits.append((idx, newline.strip()))
            changed = True
    if changed:
        out = "\n".join(lines)
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(out)
    return comment_hits, string_hits


def main():
    comment_report = []
    string_report = []
    files_changed = 0
    for dirpath, dirnames, filenames in os.walk(ROOT):
        if any(seg in dirpath for seg in (os.sep + "build", os.sep + ".gradle", os.sep + ".git")):
            continue
        for fn in filenames:
            if not fn.endswith(".java"):
                continue
            path = os.path.join(dirpath, fn)
            res = process_file(path)
            if res is None:
                continue
            comment_hits, string_hits = res
            rel = os.path.relpath(path, ROOT).replace(os.sep, "/")
            if comment_hits:
                files_changed += 1
                comment_report.append((rel, comment_hits))
            if string_hits:
                string_report.append((rel, string_hits))

    total_comment = sum(len(h) for _, h in comment_report)
    total_string = sum(len(h) for _, h in string_report)

    scratch = os.path.join(ROOT, "docs", "dev", "scratch")
    os.makedirs(scratch, exist_ok=True)
    checklist = os.path.join(scratch, "CHECKLIST-emdash-comment-review.md")
    with open(checklist, "w", encoding="utf-8", newline="\n") as f:
        f.write("# Em-dash comment review checklist\n\n")
        f.write("Auto-generated by `scripts/emdash-comment-fix.py`.\n\n")
        f.write("Em/en dashes inside Java comments were mass-replaced with ASCII "
                "hyphens as an immediate fix. This list enumerates every comment "
                "location touched so the surrounding comment prose can be reviewed "
                "session by session (trim AI-authored exposition, remove process "
                "labels, tighten to the invariant). Tick a file off once its "
                "comments have been reviewed.\n\n")
        f.write(f"- Files with comment replacements: {len(comment_report)}\n")
        f.write(f"- Total comment dashes replaced: {total_comment}\n")
        f.write(f"- String/char-literal dashes left for MANUAL review: {total_string}\n\n")
        f.write("---\n\n## Comment locations (replaced, review prose)\n\n")
        for rel, hits in sorted(comment_report):
            f.write(f"- [ ] `{rel}` ({len(hits)})\n")
            for lineno, text in hits:
                snippet = text if len(text) <= 140 else text[:137] + "..."
                f.write(f"    - L{lineno}: {snippet}\n")
        if string_report:
            f.write("\n---\n\n## String/char-literal dashes (NOT replaced - manual)\n\n")
            for rel, hits in sorted(string_report):
                f.write(f"- [ ] `{rel}` ({len(hits)})\n")
                for lineno, text in hits:
                    snippet = text if len(text) <= 140 else text[:137] + "..."
                    f.write(f"    - L{lineno}: {snippet}\n")

    print(f"[DONE] files changed: {files_changed}")
    print(f"[DONE] comment dashes replaced: {total_comment}")
    print(f"[DONE] string/char dashes left (manual): {total_string}")
    print(f"[DONE] checklist: {os.path.relpath(checklist, ROOT)}")


if __name__ == "__main__":
    main()
