#!/usr/bin/env python3
"""export-translation-bundle.py

Cross-platform (Python 3.12) replacement for export-translation-bundle.ps1.

Reads scripts/out/bleed-<lang>.tsv (produced by audit-locale-bleed.py) and
writes scripts/out/bundle-<lang>.md (or bundle-all.md with --all) - a markdown
document for an external translation session, fed back through
import-translation-bundle.py.

Each bleed row becomes one fenced bundle block. Sentinels mask anything the
translator must not change: bracketed placeholders, ampersand / hex color codes,
section markers, doc-tags, URLs. Output is UTF-8, no BOM, LF line endings.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import locale_common as lc  # noqa: E402

# Order matters: longest / most-specific first.
MASK_PATTERNS = [
    r"@(?:type|range|unit|default|options):[^\r\n]*",
    r"https?://[^\s]+",
    r"#[0-9A-Fa-f]{6}\b",
    r"&[0-9A-Fa-fk-orK-OR]",
    "\u00a7[0-9A-Fa-fk-orK-OR]?",
    r"\[[A-Za-z_][A-Za-z0-9_]*\]",
]


def mask_text(text: str, legend: list[str]) -> str:
    if not text:
        return text
    masked = text
    for pat in MASK_PATTERNS:
        def repl(m: re.Match) -> str:
            token = f"<<P{len(legend)}>>"
            legend.append(m.group(0))
            return token
        masked = re.sub(pat, repl, masked)
    return masked


def unescape_tsv_comment(s: str | None) -> str:
    if s is None:
        return ""
    return s.replace("\\n", "\n").replace("\\t", "\t")


def indent_block(s: str, prefix: str = "  ") -> str:
    if not s:
        return prefix
    return "\n".join(prefix + ln for ln in s.split("\n"))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--locale", default="")
    ap.add_argument("--all", action="store_true")
    ap.add_argument("--max-rows", type=int, default=0)
    ap.add_argument("--out-dir", dest="out_dir")
    args = ap.parse_args()

    out_dir = Path(args.out_dir) if args.out_dir else lc.out_dir()

    do_all = args.all
    if not args.locale and not args.all:
        do_all = True
    if args.locale and args.all:
        raise SystemExit("Pass either --locale <code> or --all, not both.")

    available_bleeds = sorted(out_dir.glob("bleed-*.tsv"))
    available_locales = sorted(re.sub(r"^bleed-", "", p.stem) for p in available_bleeds)

    if do_all:
        if not available_bleeds:
            raise SystemExit(f"No bleed-*.tsv manifests found in {out_dir}. Run audit-locale-bleed.py first.")
        bundle = out_dir / "bundle-all.md"
        bleed_files = available_bleeds
    else:
        bleed = out_dir / f"bleed-{args.locale}.tsv"
        bundle = out_dir / f"bundle-{args.locale}.md"
        if not bleed.exists():
            known = ", ".join(available_locales) if available_locales else "(none yet - run audit-locale-bleed.py first)"
            raise SystemExit(f"bleed-{args.locale}.tsv not found. Known locales: {known}. "
                             "To export all locales in one bundle, run with --all.")
        bleed_files = [bleed]

    sb: list[str] = []

    def line(s: str = "") -> None:
        sb.append(s)

    title_locale = "all locales" if do_all else f"`{args.locale}`"
    line(f"# Translation bundle: {title_locale}")
    line()
    line("Generated by `scripts/export-translation-bundle.py`.")
    if do_all:
        line("Sources: " + ", ".join(f"`scripts/out/{p.name}`" for p in bleed_files) + ".")
    else:
        line(f"Source manifest: `scripts/out/bleed-{args.locale}.tsv`.")
    line()
    line("## How to use this file")
    line()
    line("1. **Only edit `value_locale`, `comment_locale`, and (optionally) `key_locale`** fields in each block.")
    line("   Do not touch `locale`, `relpath`, `parent_path`, `base_key`, `index`, `sentinels`, `value_english`,")
    line("   `comment_english`, or `blank_before`. Do not reorder or delete blocks.")
    line("2. **The `locale:` field at the top of each block names the target language** (e.g. `de`, `fr`, `ja`).")
    line("   Translate `value_locale` and `comment_locale` into that language. The importer dispatches each")
    line("   block to the matching `scripts/out/locale-<locale>.tsv`.")
    line("3. **Preserve every sentinel of the form `<<P0>>`, `<<P1>>`, etc. verbatim.**")
    line("   They mask placeholders, color codes, doc-tags, and URLs that must round-trip without modification.")
    line("   The `sentinels:` field lists what each token represents - use it as a hint when ordering them")
    line("   in the translated sentence, but never inline them.")
    line("4. **Lines starting with `@type:` / `@range:` / `@unit:` / `@default:` / `@options:` are masked")
    line("   as a single sentinel** and must remain a single sentinel in the translation.")
    line("5. Leave a block as-is to skip it; the importer will re-seed those rows with a `# TODO(i18n):` marker")
    line("   so contributors can pick them up later.")
    line("6. Special locales: `cat` is **Internet Cat dialect** (not Catalan) - use the cat-themed vocabulary")
    line("   from `.junie/AGENTS.md` (e.g. `scratching_post` for database, `yarn_ball` for network).")
    line("7. Save as UTF-8 (no BOM) and feed back through:")
    if do_all:
        line("   `python scripts/import-translation-bundle.py --all`")
    else:
        line(f"   `python scripts/import-translation-bundle.py --locale {args.locale}`")
    line()
    line("## Rows")
    line()

    ordinal = 0
    per_locale_counts: dict[str, int] = {}
    for bf in bleed_files:
        lang = re.sub(r"^bleed-", "", bf.stem)
        lines = re.split(r"\r?\n", lc.read_text_no_bom(bf))
        # drop header + trailing empty entries
        data = [ln for ln in lines[1:] if ln != ""]
        if not data:
            print(f"No bleed rows for {lang}. Skipping.")
            continue
        if args.max_rows > 0:
            data = data[:args.max_rows]
        per_locale_counts[lang] = 0

        for ln in data:
            c = ln.split("\t", 7)
            if len(c) != 8:
                continue
            ordinal += 1
            per_locale_counts[lang] += 1

            relpath, parent_path, key_col, index, value_en, comment_en_raw, blank_before, base_key = c
            file = re.sub(r"^lang/[^/]+/", "", relpath)

            legend: list[str] = []
            value_masked = mask_text(value_en, legend)
            comment_raw = unescape_tsv_comment(comment_en_raw)
            comment_masked = mask_text(comment_raw, legend)

            if not legend:
                legend_str = "(none)"
            else:
                def _flatten(v: str) -> str:
                    return v.replace("\r\n", "\\n").replace("\n", "\\n")
                legend_str = "; ".join(
                    f"P{i}={_flatten(legend[i])}" for i in range(len(legend))
                )

            line(f"### {ordinal}. [{lang}] {file}::{base_key} [{parent_path}:{index}]")
            line("```bundle")
            line(f"locale:           {lang}")
            line(f"base_key:         {base_key}")
            line(f"parent_path:      {parent_path}")
            line(f"index:            {index}")
            line(f"relpath:          {relpath}")
            line(f"blank_before:     {blank_before}")
            line(f"sentinels:        {legend_str}")
            line("comment_english: |")
            line(indent_block(comment_masked, "  "))
            line(f"value_english:    {value_masked}")
            line(f"key_locale:       {key_col}")
            line(f"value_locale:     {value_masked}")
            line("comment_locale: |")
            line(indent_block(comment_masked, "  "))
            line("```")
            line()

    lc.write_bytes_utf8(bundle, "\n".join(sb) + "\n")

    print(f"Wrote {ordinal} rows -> {bundle}")
    if do_all and per_locale_counts:
        print()
        print("Per-locale row counts:")
        for k in sorted(per_locale_counts):
            print(f"  {k:<5} {per_locale_counts[k]:5}")
    print()
    print("Hand the bundle to your external translation session, save it back to the same")
    print("path, then run:")
    if do_all:
        print("  python scripts/import-translation-bundle.py --all")
    else:
        print(f"  python scripts/import-translation-bundle.py --locale {args.locale}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
