plugins {
    id 'java-library'
}
dependencies {
    api project(':rtp-api')
    api project(':rtp-core')
    compileOnly 'org.spigotmc:spigot-api:1.20.1-R0.1-SNAPSHOT'
    compileOnly 'me.clip:placeholderapi:2.11.6'
    implementation 'xyz.tozymc.spigot:title-api:1.0'
    implementation 'io.github.dailystruggle:CommandsAPI:1.0.0-RELEASE'
    testImplementation testFixtures(project(':rtp-core'))
    testImplementation 'com.github.seeseemelk:MockBukkit-v1.20:3.93.2'
}
