# Minimalny poziom logowania (drobniejszy z tego i poziomu loggera serwera).
# ALL zachowuje zachowanie identyczne z loggerem serwera.
# @type: enum
# @options: [SEVERE, WARNING, INFO, CONFIG, FINE, FINER, FINEST, ALL, OFF]
# @default: ALL
min_poziom: "INFO"

# Loguj komendy RTP wykonane przez graczy
# @type: boolean
# @default: false
polecenie: false

# Loguj udane zdarzenia teleportacji
# @type: boolean
# @default: true
teleportacja: true

# Loguj informacje, gdy wybór lokalizacji się nie powiedzie
# @type: boolean
# @default: true
niepowodzenie_wyboru: true

# Loguj RTP wywołane zmianą świata
# @type: boolean
# @default: true
zdarzenie_zmianaSwiata: true

# Loguj RTP wywołane przy dołączeniu
# @type: boolean
# @default: true
zdarzenie_dolaczenie: true

# Loguj RTP wywołane przy odrodzeniu
# @type: boolean
# @default: true
zdarzenie_odrodzenie: true

# Loguj przetwarzanie zdarzeń ruchu
# @type: boolean
# @default: true
zdarzenie_ruch: true

# Loguj przetwarzanie zdarzeń teleportacji
# @type: boolean
# @default: true
zdarzenie_teleportacja: true

# --- Przełączniki logowania pluginu ---
# Documentation: plugins/RTP/docs/admin/configuration/CONFIGURATION.md#loggingyml--console-logging-verbosity
# Loguj wszystkie pliki przeładowane podczas /rtp reload
# @type: boolean
# @default: false
szczegolowe_przeladowanie: false

# Loguj szczegóły inicjalizacji regionu
# @type: boolean
# @default: false
szczegolowa_inicjalizacjaRegionu: false

# Logi debugowania aktywności pamięci
# @type: boolean
# @default: false
system_sledzeniePamieci: false

# Logi debugowania aktywności bazy danych
# @type: boolean
# @default: false
system_bazaDanych: false

# NIE ZMIENIAJ NUMERU WERSJI
version: 1.0
