# Mindest-Log-Level (das feinere aus diesem und dem des Server-Loggers).
# ALL verhält sich identisch zum Server-Logger.
# @type: enum
# @options: [SEVERE, WARNING, INFO, CONFIG, FINE, FINER, FINEST, ALL, OFF]
# @default: ALL
minLevel: "INFO"

# Von Spielern ausgeführte RTP-Befehle protokollieren
# @type: boolean
# @default: false
befehl: false

# Erfolgreiche Teleport-Ereignisse protokollieren
# @type: boolean
# @default: true
teleportierung: true

# Informationen protokollieren, wenn die Standortauswahl fehlschlägt
# @type: boolean
# @default: true
auswahlFehlschlag: true

# RTP ausgelöst durch Weltenwechsel protokollieren
# @type: boolean
# @default: true
ereignisWeltwechsel: true

# RTP ausgelöst beim Beitritt protokollieren
# @type: boolean
# @default: true
ereignisBeitritt: true

# RTP ausgelöst beim Respawn protokollieren
# @type: boolean
# @default: true
ereignisRespawn: true

# Verarbeitung von Bewegungsereignissen protokollieren
# @type: boolean
# @default: true
ereignisBewegung: true

# Verarbeitung von Teleport-Ereignissen protokollieren
# @type: boolean
# @default: true
ereignisTeleport: true

# --- Plugin-Logging-Einstellungen ---
# Dokumentation: plugins/RTP/docs/admin/configuration/CONFIGURATION.md#loggingyml--console-logging-verbosity
# Protokolliert alle Dateien, die während /rtp reload neu geladen wurden
# @type: boolean
# @default: false
detailliertesNeuladen: false

# Details zur Regionsinitialisierung protokollieren
# @type: boolean
# @default: false
detaillierteRegionsInitialisierung: false

# Debug-Protokolle für Speicheraktivität
# @type: boolean
# @default: false
systemSpeicherTracker: false

# Debug-Protokolle für Datenbankaktivität
# @type: boolean
# @default: false
systemDatenbank: false

# ÄNDERE NICHT DIE VERSIONSNUMMER
version: 1.0
