#basic UX configuration

#time, in seconds, to delay teleportation
# allows server some time to preload the chunks
teleportDelay: 2

#how far a player can move before teleportation cancels, in meters/blocks
cancelDistance: 2

#attempt cooldown, in seconds, to prevent spam
teleportCooldown: 300

#list of commands to run after any teleportation
# e.g.
#consoleCommands:
#  - "say Someone Teleported!"
consoleCommands:
playerCommands:

#DO NOT TOUCH VERSION NUMBER
version: "3.0"

database:
  # Available types: yaml, sqlite, h2, mysql, postgresql
  type: "sqlite"
  # Network database credentials (ignored if type is yaml, sqlite or h2)
  host: "127.0.0.1"
  port: 3306
  name: "rtp"
  username: "root"
  password: "password"

network:
  redis:
    enabled: false
    host: "127.0.0.1"
    port: 6379
    password: ""
